version: '3.8'
services:
  backend:
    container_name: back-rediux
    build: ./RediUX-Back
    image: rediux_backend
    ports:
      - "3000:3000"
    networks:
      - rediux-network
  database:
    image: postgres:latest
    container_name: database_rentx
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rediux
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rediux-network

  frontend:
    container_name: front-rediux
    build: ./RediUX-Front
    image: rediux_frontend
    ports:
      - "8080:3000"
    networks:
      - rediux-network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  rediux-network:
    driver: bridge
    
