version: '3.8'

services:
  backend:
    container_name: back-rediux
    build: ./RediUX-Back
    image: rediux_backend
    ports:
      - "3000:3000"
    volumes:
      - ./RediUX-Back:/usr/app
      - /usr/app/node_modules
    networks:
      - rediux-network
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rediux
    depends_on:
      - database

  frontend:
    container_name: front-rediux
    build: ./RediUX-Front
    image: rediux_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./RediUX-Front:/usr/app
      - /usr/app/node_modules
    networks:
      - rediux-network
    depends_on:
      - backend

  database:
    image: postgres:16
    container_name: database_rediux
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rediux
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rediux-network

volumes:
  postgres_data:

networks:
  rediux-network:
    driver: bridge