version: '3.8'
services:
  backend:
    container_name: back-rediux
    build: ./RediUX-Back
    command: npm run dev
    image: rediux_backend
    ports:
      - "3000:3000"
    volumes:
      - ./RediUX-Back:/usr/app
    networks:
      - rediux-network
    depends_on:
      - database
      
  database:
    image: postgres:latest
    container_name: database_rediux
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rediux
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rediux-network

volumes:
  postgres_data:

networks:
  rediux-network:
    driver: bridge